---
- name: Check Docker Container Health
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Get list of running container IDs
      command: docker ps -q
      register: running_containers
      changed_when: false

    - name: Check health status for each container
      command: docker inspect --format='{{.Name}}: {{if .State.Health}}{{.State.Health.Status}}{{else}}no health check defined{{end}}' {{ item }}
      loop: "{{ running_containers.stdout_lines }}"
      register: container_health
      changed_when: false

    - name: Display container health statuses
      debug:
        msg: "{{ container_health.results | map(attribute='stdout') | list }}"
