---
- name: Manage Windows Updates
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check for and install critical and security updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: yes
      register: update_results

    - name: Display update results
      debug:
        var: update_results
