---
- name: Scan for available Windows updates
  hosts: windows
  gather_facts: no
  tasks:
    - name: Search for available updates without installing them
      ansible.windows.win_updates:
        state: searched
      register: update_scan

    - name: Display update scan results
      debug:
        msg: >
          {% if update_scan.found_update_count > 0 %}
            Found {{ update_scan.found_update_count }} updates:
            {{ update_scan.updates | to_nice_json }}
          {% else %}
            No updates available.
          {% endif %}
