---
- name: Ensure folder C:\repo\test exists on Windows with detailed output
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create folder C:\repo\test if it does not exist
      win_file:
        path: C:\repo\test
        state: directory
      register: folder_result

    - name: Display folder creation result
      debug:
        msg: >
          Folder 'C:\repo\test' 
          {% if folder_result.changed %}
            has been created.
          {% else %}
            already exists.
          {% endif %}
